### ISSUE TITLE
Testes automatizados

### ISSUE THREAD

**Issue by edinhodiluviano** [AlanTaranti/sidrapy#140]
Seria interessante adicionar testes automatizados para garantir execução dos testes em todas as versões do python.
Acredito que o github actions seja uma ferramenta interessante pra isso.
Caso queira, ja fiz um código pra isso, posso enviar o PR.

Ps.: Inclusive ao rodar os códigos, do zero, com as configurações atuais descobri que o numpy não suporta mais o python 3.7. Nesse caso sugeriria tb ja remover o suporte ao python 3.7. Tenho um commit pra isso tb, caso queira.

**Comment by AlanTaranti** [comment]
Olá @edinhodiluviano 

Hoje já existem testes no projeto em: https://github.com/AlanTaranti/sidrapy/tree/master/tests

Eles são executados via tox nas versões do python 3.7 até a 3.10. Mas seria muito válido adicionar suporte ao python 3.11, aumentar a cobertura de testes e integrar com o GitHub Actions.

Sobre a remoção suporte ao python 3.7, talvez seja interessante uma consulta à comunidade, já que essa versão do python ainda é oficialmente suportada pela PSF.

**Comment by edinhodiluviano** [comment]
Criada a [integração](https://github.com/edinhodiluviano/sidrapy/commit/ea65ecbba397379f773da8e0e1592c8b4d04840f) com o github actions. Mas ela não passa com o python3.7.
O [numpy ja não suporta mais o python 3.7](https://pypi.org/project/numpy/), logo ele não instala e da erro.

Posso enviar a integração com os testes sem passar (com o github actions). Ou posso enviar a integração sem os testes para o 3.7.
Como vc achar melhor : )

**Comment by AlanTaranti** [comment]
Entendo. Pode submeter a PR sim, @edinhodiluviano, só ajusta por gentileza, o README e o setup.cfg para ficar claro a remoção do suporte ao python 3.7.

**Comment by edinhodiluviano** [comment]
Ok. Enviada.
Os testes unitários estão no github actions. Tb modifiquei o suporte ao 3.7 em todos os locais que encontrei.
Ainda falta adicionar os testes estaticos (linters, black, etc). Mas acredito que seja melhor outra PR só pra eles.

**Comment by AlanTaranti** [comment]
Rodaram as actions corretamente @edinhodiluviano 

Muito obrigado 😊

https://github.com/AlanTaranti/sidrapy/actions/workflows/main_workflow.yml

**Comment by AlanTaranti** [comment]
Fechando essa issue, caso necessário podemos abrir novamente
