### ISSUE TITLE
Erro SSL ao realizar consulta de tabela

### ISSUE THREAD

**Issue by AlanTaranti** [AlanTaranti/sidrapy#88]
Recentemente, o IBGE trocou o certificado SSL de seus sites, incluindo o SIDRA.

Nessa troca, por algum motivo a validação do certificado pelo **requests**, dependência do sidrapy, não ocorre de maneira satisfatória.

Caso esteja com esse erro, a solução paliativa é atualizar o sidrapy para a versão 0.1.3 ou superior e passar o parametro **verify_ssl=False** no **get_table**, conforme exemplo abaixo.

```
sidrapy.get_table(
    table_code="6588",
    territorial_level="1",
    ibge_territorial_code="all",
    classifications={"48": "39428"},
    period="last",
    verify_ssl=False,
)
```

![image](https://user-images.githubusercontent.com/9096525/170621097-ad9cf27c-6312-4b8a-99b5-d0ce19ac0896.png)

**Comment by nicmorais** [comment]
Olá. Eu testei o parâmetro verify_ssl=False e não funcionou. Também fora do pacote sidrapy, o parâmetro verify=False no requests também não resolveu. Eu consegui contornar a situação com a solução descrita [aqui](https://stackoverflow.com/a/71646353), no StackOverflow. O problema está no serviço do IBGE, que não suporta a [RFC 5746](https://www.rfc-editor.org/rfc/rfc5746) até o presente momento.

**Comment by AlanTaranti** [comment]
Muito obrigado pela sugestão @nicmorais

**Comment by AlanTaranti** [comment]
A correção entra na próxima release na segunda-feira.

A próxima versão pode ser testada com:
`pip install -i https://test.pypi.org/simple/ sidrapy==0.1.4`
